// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPnr4iGcVR7j64woMJBeH7EUWycu4n38',
    appId: '1:1021728352676:web:be6c26b8a84da479637931',
    messagingSenderId: '1021728352676',
    projectId: 'flutter-projects-24fe2',
    authDomain: 'flutter-projects-24fe2.firebaseapp.com',
    storageBucket: 'flutter-projects-24fe2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNi9PZbyTOvVed2lTRJZn4NCPpZf4H3Y',
    appId: '1:1021728352676:android:585edeedf59efec6637931',
    messagingSenderId: '1021728352676',
    projectId: 'flutter-projects-24fe2',
    storageBucket: 'flutter-projects-24fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2Znk8H3TEQ-i6pXeuqCWiS32JBrIJNk',
    appId: '1:1021728352676:ios:cb4637b7d404f8ac637931',
    messagingSenderId: '1021728352676',
    projectId: 'flutter-projects-24fe2',
    storageBucket: 'flutter-projects-24fe2.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2Znk8H3TEQ-i6pXeuqCWiS32JBrIJNk',
    appId: '1:1021728352676:ios:cb4637b7d404f8ac637931',
    messagingSenderId: '1021728352676',
    projectId: 'flutter-projects-24fe2',
    storageBucket: 'flutter-projects-24fe2.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPnr4iGcVR7j64woMJBeH7EUWycu4n38',
    appId: '1:1021728352676:web:e4707c55cb62097d637931',
    messagingSenderId: '1021728352676',
    projectId: 'flutter-projects-24fe2',
    authDomain: 'flutter-projects-24fe2.firebaseapp.com',
    storageBucket: 'flutter-projects-24fe2.firebasestorage.app',
  );
}
